#!/bin/python
#This is intended to be called on a pre-commit action to automatically convert your markdown to html

import markdown
import os

tempHTML = markdown.markdown(open(os.path.dirname(os.path.realpath(__file__))+"/master_documentation.md","r").read())
open(os.path.dirname(os.path.realpath(__file__))+"/master_documentation.html","w").write("<!--This is an autogenerated file. Use convert.py to generate-->\n<link rel=\"stylesheet\" href=\"style.css\"></link>\n" + tempHTML)